server:
  port: 8080
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: none #update #create-drop #none
    database: mysql
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3310/rookie
    username: root
    password: rookie
    hikari:
      maximumPoolSize: 10

##### Resttemplate #####
rest:
  timeout: 30
  github:
    get-user: https://api.github.com/users/
